### ISSUE TITLE
socket command

### ISSUE THREAD

**Issue by notXploit** [Malam-X/DragonMS#2]
when i run the script show me this error
Traceback (most recent call last):
  File "/home/kali/Desktop/DragonMS/main.py", line 208, in <module>
    private_ip   = socket.gethostbyname(socket.gethostname())
NameError: name 'socket' is not defined

**Comment by Malam-X** [comment]
> when i run the script show me this error Traceback (most recent call last): File "/home/kali/Desktop/DragonMS/main.py", line 208, in private_ip = socket.gethostbyname(socket.gethostname()) NameError: name 'socket' is not defined

Done
